name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        type: string
        default: "varshitha"

      age:
        description: "Age"
        type: number
        required: true

      gender:
        description: "Gender"
        type: choice
        options:
          - male
          - female

      married:
        description: "Is married?"
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"

      - name: Age
        run: echo "${{ inputs.age }}"

      - name: Gender
        run: echo "${{ inputs.gender }}"

      - name: Married
        run: echo "${{ inputs.married }}"
